version: '3'
services:
  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432

  docockroachdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 26257:26257
      - 9999:9999